### ISSUE TITLE
Addition of sim-udp transport

### ISSUE THREAD

**Issue by dmnewbold** [ipbus/ipbus-firmware#105]
A long overdue feature is a simulation interface to uHAL using UDP packets rather than raw ethernet. This will avoid the need for root access when running the sim (currently required to set up and use the ethernet loopback interface) and will speed up the sim by avoiding the need to emulate the ethernet decoder block.

This patch will create a new transport, sim_udp, which will use the modelsim FLI interface to provide a UDP socket connection to uHAL.

**Comment by tswilliams** [comment]
This new interface was included in the v1.4 release, under a new directory `components/modelsim_fli/transport_udp`; at the same time, the pre-existing raw Ethernet modelsin interface was moved to `components/modelsim_fli/eth`.

Closing.
