### ISSUE TITLE
zcu102_basex project ...  which version of vivado was this originally built with?

### ISSUE THREAD

**Issue by kjazatlas** [ipbus/ipbus-firmware#177]
hi,
i have been trying to build zcu102_basex project following the instructions here
https://ipbus.web.cern.ch/ipbus/doc/user/html/firmware/exampleDesigns.html
i tried both with vivado 2018.3 and 2015.4.  in the former all the steps completed but the
project did not build. in part because the autoupdate of the ethernet ip was not successful.
in the latter, the project does not make at the make-project step as i get the error xczu9eg-ffvb1156-2-e part not found.
my question is, is there a version of vivado that would build this out of the box?  which version was this originally tested with? thanks in advance for your help and suggestions.

**Comment by tswilliams** [comment]
Hi,

The example designs for the last release were built using Vivado 2018.3 and 2019.1. In particular, the specific version of 2018.3 used in current automated builds (as printed when starting vivado) is:

> ****** Vivado v2018.3.1 (64-bit)
>   **** SW Build 2489853 on Tue Mar 26 04:18:30 MDT 2019
>   **** IP Build 2486929 on Tue Mar 26 06:44:21 MDT 2019

> i tried both with vivado 2018.3 and 2015.4. in the former all the steps completed but the
project did not build. in part because the autoupdate of the ethernet ip was not successful.

Can you clarify what you mean by "the project did not build"? E.g. Did errors occur during implementation/synthesis? Was a bitfile produced?



Cheers,
Tom

**Comment by kjazatlas** [comment]
hi,
a.  thank you for responding so quickly!!  unfortunately i am going to be offline for 2 days and i overwrite the 2018.3
version with 2015.4.  but what i had from my first try is below.  if that is not sufficient, i can reproduce, but probably not until sun.
![image1](https://user-images.githubusercontent.com/16338606/85802576-13e3d900-b6fa-11ea-9d59-f935ec24e887.png)
![image](https://user-images.githubusercontent.com/16338606/85802623-2f4ee400-b6fa-11ea-8acc-1600a0017359.png)
![image](https://user-images.githubusercontent.com/16338606/85802705-53aac080-b6fa-11ea-8b41-87b4b0d400be.png)
let me know if you can see these.  thanks..kj

**Comment by alessandrothea** [comment]
Hi, have you ruled out a licence problem?
Those are ip cores that require specific licences, if I'm not mistaken.

**Comment by kjazatlas** [comment]
i am still working on this.  trying to resolve possible license issues that are preventing the building of the bitfile.

**Comment by kjazatlas** [comment]
hi,
a.  thanks again for your help and suggestion.
b.  yes, there was an odd license issue that we resolved.  and also we had to use only broadcom sfp module.  anyway, the example worked out of the box as advertised.
