### ISSUE TITLE
ipbus-firmware link changed 

### ISSUE THREAD

**Issue by shu-soleil** [ipbus/ipbus-firmware#188]
https://github.com/ipbus/ipbus-firmware/blob/master/projects/xilinx/README.md :
"ipbb add git https://github.com/ipbus-firmware" needs to be changed to "ipbb add git https://github.com/ipbus/ipbus-firmware"

**Comment by tswilliams** [comment]
Hi,

Thanks for reporting this. I've now fixed that README.

Cheers,
Tom
