### ISSUE TITLE
error message for ipbus_dpram in VIVADO 2017.4

### ISSUE THREAD

**Issue by mkrivda** [ipbus/ipbus-firmware#59]
I am using ipbus fw 1.2.
I have upgraded VIVADO 2016.2. to VIVADO 2017.4 and I am getting error message for ipbus_dpram.

![error_ipbus_dpram_vivado2017 4](https://user-images.githubusercontent.com/33321933/43138145-3fd89e04-8f4e-11e8-8ccd-d83278ae76e6.png)

**Comment by mkrivda** [comment]
![error_ipbus_dpram_vivado20174_details](https://user-images.githubusercontent.com/33321933/43139473-14312eac-8f52-11e8-80ec-67f937741e1b.JPG)

**Comment by dmnewbold** [comment]
Man that is the nicest formatted bug report ever. If only all bug reports were like this 8-)

**Comment by dmnewbold** [comment]
Fixing now.

**Comment by tswilliams** [comment]
The fix for this bug was just merged into the `master` branch. Closing the ticket now. @mkrivda , let us know if you still see any related problems.

Thanks,
Tom
