### ISSUE TITLE
ipbus_peephole_ram, is it still a thing?

### ISSUE THREAD

**Issue by alessandrothea** [ipbus/ipbus-firmware#84]
The peephole ram slave seems to have been superseded by the ported dual-port ram slave.
Is that correct? Can the peephole ram be deleted in such case?

Alessandro

**Comment by alessandrothea** [comment]
Good point, thanks for the reminder.

**Comment by alessandrothea** [comment]
After comparing once more `ipbus_peephole_ram` and `ipbus_ported_dram`, I remembered the difference. The peephole is completely contained in the ipbus clock domain. So was it created for testing purposes only? Or does it have any other use?

**Comment by dmnewbold** [comment]
Yes, testing purposes only. You can of course get the same effect by using one of the other RAM blocks and just not connecting the other port to anything useful.


Prof David M Newbold | Director Particle Physics Department
STFC Rutherford Appleton Laboratory, Harwell Campus,  Didcot OX11 0QX United Kingdom
Tel | Office: +44 (0) 1235 446760        Tel | Mobile: +44 (0) 7542 226292
Email | dave.newbold@stfc.ac.uk<mailto:dave.newbold@stfc.ac.uk>       http://www.stfc.ukri.org<http://www.stfc.ukri.org/>
[STFC-UKRI1]
www.ukri.org<http://www.ukri.org/>  STFC is a member of UK Research and Innovation

**Comment by alessandrothea** [comment]
Undestood. The same reasoning applies to `ipbus_ram` I guess.

**Comment by dmnewbold** [comment]
Looks that way.


Prof David M Newbold | Director Particle Physics Department
STFC Rutherford Appleton Laboratory, Harwell Campus,  Didcot OX11 0QX United Kingdom
Tel | Office: +44 (0) 1235 446760        Tel | Mobile: +44 (0) 7542 226292
Email | dave.newbold@stfc.ac.uk<mailto:dave.newbold@stfc.ac.uk>       http://www.stfc.ukri.org<http://www.stfc.ukri.org/>
[STFC-UKRI1]
www.ukri.org<http://www.ukri.org/>  STFC is a member of UK Research and Innovation
